name: Publish Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/

    - name: Publish ManagedXZ
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/ManagedXZ/ManagedXZ.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          
          
          
