name: Publish packages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Nuget

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
      
    - name: Materialize Signing Key
      id: write_sign_key_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'SoftFx.snk'
        encodedString: ${{ secrets.SOFTFX_CERT }}

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/
      env:
        SignAssembly: true
        AssemblyOriginatorKeyFile: ${{ steps.write_sign_key_file.outputs.filePath }}

    - name: Publish SharpRpc.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/SharpRpc/SharpRpc.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: Publish SharpRpc.Builder
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/SharpRpc.Builder/SharpRpc.Builder.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          
          
          
